# Generated by Django 2.2.6 on 2019-10-13 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authoritydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=500)),
                ('users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('mycredits', models.IntegerField(default=0)),
                ('mypoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='locationdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('pic', models.ImageField(blank=True, upload_to='images/')),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userdata')),
            ],
        ),
    ]
